# Generated by Django 4.1.7 on 2023-03-29 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_accountvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='account',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='attendees.accountvo'),
            preserve_default=False,
        ),
    ]
