# Generated by Django 4.1.7 on 2023-03-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_attendee_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='account',
        ),
    ]
